apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourname
  labels:
    tier: yourname
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: yourname
  template:
    metadata:
      labels:
        tier: yourname
    spec:
      containers:
      - name: web
        image: jaibw/demowebsite:yourname-buildnumber
---
apiVersion: v1
kind: Service
metadata:
  name: yourname
spec:
  type: NodePort
  selector:
    tier: yourname
  ports:
    - port: 80
      targetPort: 80
